version: '3.8'
services:
  backend:
    image: asthaissrani/fashion-backend:v1
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env  # This loads your Mongo Atlas URI from your existing .env file
    restart: always

  frontend:
    image: asthaissrani/fashion-frontend:v1
    ports:
      - "80:80"
    depends_on:
      - backend